// Builds src/imdbData.ts: a compact, sorted list of IMDb ratings for every movie with
// enough votes, bundled in the app so ratings show instantly without any API call.
// Source: IMDb's non-commercial datasets (https://datasets.imdbws.com, refreshed daily;
// personal, non-commercial use only — so the generated file is git-ignored).
//
//   node scripts/imdb-ratings.mjs          download + build (run before building an APK)
//   node scripts/imdb-ratings.mjs --stub   write an empty file only if none exists (postinstall)
import { existsSync, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { createGunzip } from 'node:zlib';
import { Readable } from 'node:stream';

const OUT = new URL('../src/imdbData.ts', import.meta.url);
const MIN_VOTES = 50;
// Title types TMDB also lists as movies (incl. shorts for the "< 30 min" filter).
const TYPES = new Set(['movie', 'tvMovie', 'video', 'short', 'tvSpecial']);

const write = (data, built) => writeFileSync(OUT,
  '// Generated by scripts/imdb-ratings.mjs — do not edit. Data courtesy of IMDb (personal use).\n'
  + '// Fixed-width records sorted by id: 8-digit IMDb number + rating × 10 as 2 digits (max 99).\n'
  + `export const IMDB_BUILT = ${JSON.stringify(built)};\n`
  + `export const IMDB_DATA = ${JSON.stringify(data)};\n`);

if (process.argv.includes('--stub')) {
  if (!existsSync(OUT)) write('', '');
  process.exit(0);
}

async function* lines(file) {
  const res = await fetch(`https://datasets.imdbws.com/${file}`);
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
  const rl = createInterface({ input: Readable.fromWeb(res.body).pipe(createGunzip()), crlfDelay: Infinity });
  let first = true;
  for await (const line of rl) {
    if (first) { first = false; continue; }
    yield line.split('\t');
  }
}

const ratings = new Map();
for await (const [id, avg, votes] of lines('title.ratings.tsv.gz')) {
  if (Number(votes) >= MIN_VOTES) ratings.set(id, Math.min(99, Math.round(Number(avg) * 10)));
}
console.log(`ratings with ≥${MIN_VOTES} votes: ${ratings.size}`);

const rows = [];
for await (const [id, type] of lines('title.basics.tsv.gz')) {
  const r = ratings.get(id);
  if (r != null && TYPES.has(type)) rows.push([Number(id.slice(2)), r]);
}
rows.sort((a, b) => a[0] - b[0]);
const data = rows.map(([n, r]) => String(n).padStart(8, '0') + String(r).padStart(2, '0')).join('');
write(data, new Date().toISOString().slice(0, 10));
console.log(`wrote ${rows.length} movies (${(data.length / 1024 / 1024).toFixed(1)} MB) to src/imdbData.ts`);
